tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8001

spring:
  profiles:
    active: debug  
  redis:
    host: http://127.0.0.1
    port: 6379
---
spring:
  profiles: debug
  datasource:
    username: 
    password: 
    driver-class-name: oracle.jdbc.OracleDriver
    url:   
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring:
  profiles: release
  datasource:
    username: 
    password: 
    driver-class-name: oracle.jdbc.OracleDriver
    url: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"  
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token
jasypt:
  encryptor:
    bean: jasyptStringEncryptor        